version: "3.9"

services:
  trb-trb-auth:
    container_name: trb-auth
    build: ./
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8086:8080"
    env_file: 
      - .env